### ISSUE TITLE
Graphical editor issue on Mac

### ISSUE THREAD

**Issue by dmulholl** [milkey-mouse/edit#3]
Hi, thanks for this library. I've been trying it on a Mac and I've noticed that it works perfectly for terminal editors like vim, nano, or pico, but not for graphical editors like Sublime Text or VS Code. 

For graphical editors, I find it opens the correct editor but the opened file is blank. Also, it returns the original, unaltered text to the terminal immediately without waiting for the editor to close.

I've seen this same behaviour with Sublime Text, VS Code, and Atom. 

(Running the `edit 0.1.2` test binary on macOS Catalina.)

Thanks.

**Comment by twilligon** [comment]
I think what's happening here is as a GUI application, these editors by default fork/open a new instance and return without blocking, unlike the editors I've tested on Linux and Windows. (I don't have a Mac, so I was essentially flying blind with the macOS implementation.)

According to [this](https://osxdaily.com/2007/02/01/how-to-launch-gui-applications-from-the-terminal/) modern versions of the `open` tool support the `-W` flag to block until closing, and individual editors often have their own flags. For some editors this might be necessary on other operating systems as well.

If you are manually setting `EDITOR` to the executable name of each editor for testing, that won't work because the editors won't get a "block until close" flag. Can you run the `edit` example with these values of `EDITOR` and tell me which ones work correctly?

    cd edit
    EDITOR="open -Wt" cargo run
    EDITOR="subl -w" cargo run
    EDITOR="code -w" cargo run
    EDITOR="atom --wait" cargo run

**Comment by dmulholl** [comment]
Great, I think you've cracked it. You're right - I was setting `EDITOR` to the bare binary name. Adding the wait flag makes all the editors I tried block until closed.

    EDITOR="open -Wt" cargo run
    EDITOR="open -We" cargo run

Both of these open in TextEdit and work as expected.

    EDITOR="subl -w" cargo run

Opens in Sublime Text and works as expected.

    EDITOR="code -w" cargo run

Opens in VS Code and works as expected.

    EDITOR="atom --wait" cargo run

Opens in Atom and works as expected.

Thanks!

**Comment by twilligon** [comment]
I pushed the WIP fix to [`graphical-editor-flags`](https://github.com/milkey-mouse/edit/tree/graphical-editor-flags), but I don't have time right now to do the same for platforms other than Mac or test it.

**Comment by dmulholl** [comment]
Looks good to me. I've tested it on my Mac and the `-w` flags are working as expected for `code` and `atom`.

You can add a `-w` flag to the `subl` command too for Sublime Text on Mac. The test binary works as expected with the flag but not without.

For my own use case I've added a note to my documentation letting users know that they may need to add a `-w` flag to their `$EDITOR` variable if they want to use a graphical editor: http://www.dmulholl.com/dev/vimv.html.

**Comment by twilligon** [comment]
This has likely been fixed by #1 which finally merged my `graphical-editor-flags` branch.
